version: "3"
services:
  
  install:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    command: /bin/bash -c "npm run release; /bin/bash"
    
  dev:  
    build: .
    working_dir: /home
    ports:
      - "8080:8080"
    volumes:
      - .:/home
      - m2:/root/.m2
    command: /bin/bash
    
volumes:
  m2:
