version: "3"

volumes:
  m2:
    
services:
  install:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: "cp /app/clariform.js /home"
  
  console:  
    build: .
    working_dir: /home
    volumes:
      - $PWD:/home
      - m2:/root/.m2
    networks:
      - default
    entrypoint: /bin/bash
      
  clariform:  
    build: .
    working_dir: /home
    volumes:
      - .:/clariform
      - $PWD:/home
      - m2:/root/.m2
    entrypoint: node /app/clariform.js
          
  watch:  
    build: .
    working_dir: /home
    networks:
      - default
    ports:
      - "9630:9630"
    expose:
      - "9090:9090"
      - "9099:9099"
    volumes:
      - .:/home
      - m2:/root/.m2 
    ## NOTE shadow-cljs apparently ignores config-merge, relying on :host from shadow-cljs.edn 
    entrypoint: npx shadow-cljs watch script --config-merge '{:http {:host "watch-xxx"}}'
    
  runtime:
    build: .
    working_dir: /home
    depends_on:
      - watch
    volumes:
      - .:/home
      - m2:/root/.m2
    networks:
      - default 
    entrypoint: ["node", "out/runtime.js"]
    
  test:
    build: .
    working_dir: /home
    depends_on:
      - watch
    volumes:
      - .:/home
      - m2:/root/.m2
    networks:
      - default
    entrypoint: npx shadow-cljs compile test --config-merge '{:http {:host "watch"}}'
    
  release:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: "npm run release"
    
  repl:
    build: .
    working_dir: /home
    depends_on:
      - watch
      - runtime
    volumes:
      - .:/home
      - m2:/root/.m2
    networks:
      - default 
    # TODO incomplete as shadow-cljs ignores the overide of host instead connecting to localhost      
    entrypoint: npx shadow-cljs cljs-repl script --config-merge '{:http {:host "watch"}}'
