version: "3"
services:
  
  build:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
    command: /bin/bash -c "npm run release; echo 'alias clariform=\"node out/clariform.js\"' >> ~/.bashrc; /bin/bash"
    
  dev:  
    build: .
    working_dir: /home
    ports:
      - "8080:8080"
    volumes:
      - .:/home
    command: /bin/bash
