version: "3"
services:
  
  install:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: "cp /app/clariform.js /home"
  
  console:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: /bin/bash
  
  clariform:  
    build: .
    working_dir: /home
    volumes:
      - .:/clariform
      - $PWD:/home
      - m2:/root/.m2
    entrypoint: node /app/clariform.js
    
  dev:  
    build: .
    working_dir: /home
    stdin_open: true
    tty: true
    ports:
      - "9630:9630"
      - "9090:9090"
      - "9099:9099"
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: npx shadow-cljs watch script --config-merge "{:socket-repl {:port 9090} :nrepl {:port 9099}}"
    
  repl:
    build: .
    working_dir: /home
    depends_on:
      - dev
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: npx shadow-cljs cljs-repl script
  
volumes:
  m2:
