version: "3.9"

volumes:
  m2:
  .cpcache:
  .shadow-cljs:

networks:
  server:
    
services:
  server:
    container_name: server  
    image: ghcr.io/njordhov/docker-shadow-cljs:v0.2
    networks:
      - server
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9630"]
      interval: 10s
      timeout: 30s
      retries: 12
    ports:
      - "9630:9630" 
      - "9090:9090"
      - "9099:9099"
      - "8080:8080"
    volumes:
      - .:/home
      - m2:/root/.m2
      - .cpcache:/tmp/.cpcache
      - .shadow-cljs:/tmp/.shadow-cljs
    working_dir: /home
    entrypoint: 
      - npx
      - shadow-cljs 
      - server
  
  shadow-cljs:
    image: ghcr.io/njordhov/docker-shadow-cljs:v0.2
    depends_on:
      server:
        condition: service_healthy
    networks:
      - server
    network_mode: service:server
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
      - .cpcache:/tmp/.cpcache
      - .shadow-cljs:/tmp/.shadow-cljs
    entrypoint: 
      - npx
      - shadow-cljs 
      
  ## ------- 
  
  install:  
    image: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: "cp /app/clariform.js /home"
      
  clariform:  
    build: .
    working_dir: /home
    volumes:
      - .:/clariform
      - $PWD:/home
      - m2:/root/.m2
    entrypoint: node /app/clariform.js
    
  release:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: "npm run release"
