version: "3"
services:
  
  install:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: "cp /app/clariform.js /home"
  
  console:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: /bin/bash
  
  clariform:  
    build: .
    working_dir: /home
    volumes:
      - .:/clariform
      - $PWD:/home
      - m2:/root/.m2
    entrypoint: node /app/clariform.js
    
  dev:  
    build: .
    working_dir: /home
    ports:
      - "8080:8080"
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: /bin/bash
    
volumes:
  m2:
