version: "3"
services:
  
  install:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: /bin/bash -c "npx shadow-cljs release script; /bin/bash"
  
  clariform:  
    build: .
    working_dir: /home
    volumes:
      - .:/clariform
      - $PWD:/home
      - m2:/root/.m2
    entrypoint: node /clariform/clariform.js
    
  dev:  
    build: .
    working_dir: /home
    ports:
      - "8080:8080"
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: /bin/bash
    
volumes:
  m2:
